# Generated by Django 6.0.4 on 2026-04-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('formacao', models.TextField()),
                ('experiencia', models.TextField()),
                ('certificados', models.TextField(blank=True)),
                ('habilidades', models.TextField()),
                ('idiomas', models.TextField()),
            ],
        ),
    ]
